### PR TITLE
Bump @actions/core version

### LINKED ISSUE #201: [MAINT]: Bump @actions/core version
### Describe the need

Please consider bumping version of '@actions/core' dependency? Github [recommends](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) using `1.10.0` of `@actions/core`.

### SDK Version

_No response_

### API Version

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by tkorenko**
Please consider bumping version of '@actions/core' dependency? Github [recommends](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) using `1.10.0` of `@actions/core`.

Resolves #201 

`Type: Maintenance`

### CODE REVIEW

**Comment by nickfloyd** [comment]
Hey @tkorenko I'd like to help you try to get this in... I have a merge commit ready to go, but it looks like you don't have owner fork access enabled on your fork.  You can resolve the merge conflict or enable fork access, and I can knock it out, and I'll look at it once CI passes.  I'm good with either way.  Thanks for this change ❤️

**Comment by wolfy1339** [comment]
You won't be able to simply edit the repository through the GitHub website, as `package-lock.json` also need updating

**Comment by oscard0m** [comment]
Version 1.10.0 of `@actions/core` was landed in October 2022:
- PR: https://github.com/octokit/graphql-action/pull/159
- Git blame: https://github.com/octokit/graphql-action/blame/main/package-lock.json#L24

Dependencies are regularly updated by RenovateBot.

@tkorenko are you experiencing an issue that makes you suspect an outdated version of `@actions/core` could be the reason?

**Comment by tkorenko** [comment]
@oscard0m , nope, I'm just following Github's recommendations.

**Comment by oscard0m** [comment]
> @oscard0m , nope, I'm just following Github's recommendations.

Ok, thanks for the clarification.

If I'm correct, the version of `@actions/core` is already up to date so we would not need this PR:
- `package-lock.json` is pointing to the desired version of `@actions/core`
- The version range in `package.json` is satisfied so Renovate will keep this up to date. 

Still, I think it's interesting the second change you apply with `ncc`:

```diff
- @zeit/ncc
+ @vercel/ncc
```

The package [is deprecated](https://www.npmjs.com/package/@zeit/ncc) and it needs to consume `@vercel/ncc`:

image

I would modify this PR to tackle this change (or open a new one). What do you think @tkorenko ?

**Comment by tkorenko** [comment]
Please, correct what needs to be corrected.

**Comment by oscard0m** [comment]
Closing in favor of https://github.com/octokit/graphql-action/issues/206

**Pull request closed without merging**
