### PR TITLE
feat: support mediaType parameter for API previews

### LINKED ISSUE #16: Cannot set header information
Hi, i like your client for github, but i'm struggling to pass the accept parameter on header in order to use packages-preview api.
I've tried different approaches but i can't put it working.
Maybe if you put some examples how to customize the header on your documentation.

Best Regards,.

### PR DESCRIPTION
**Pull request by os-jsplopes**
Create a parse method to handle with json type input parameters.
Also included in this method the previous change regarding integers.

fixes #16.

As was spoke in the issue thread it would be great to have the **previous ** array option that is available on [octokit/core](https://github.com/octokit/core.js#hooks), but due to lack of time to test and develop this solution will handle it for now.

### CODE REVIEW

**Comment by gr2m** [comment]
Could you please try the same approach as in this PR?

Basically instead of 

```js
result[inputName] = value
```

do 

```js
result[inputName] = yaml.safeLoad(value);
```

The code in `request-action` also supports the `mediaType` option, which allows to set previews more easily, maybe worth adding?

**Comment by os-jsplopes** [comment]
Hy, Gregor updated to the safeload approach.
The header parameter is now working 😄.
But the **medaType previews** weren't, but after some digging i have found the issue and it is in the [octokit/graphql](https://github.com/octokit/graphql.js) project so i will apply the fix there.

After fixing locally tested both scenarios with success 🥳 .

**Comment by gr2m** [comment]
Thanks @os-jsplopes! Similar to my comment at https://github.com/octokit/graphql.js/pull/84#pullrequestreview-406019706, we should add a test for a query that uses a `mediaType` parameter, it would go in here: https://github.com/octokit/graphql-action/blob/master/.github/workflows/test.yml

**Comment by os-jsplopes** [comment]
@gr2m 
Test implemented. 😄 👍

**Comment by gr2m** [comment]
Thanks, test looks great 👍 Once we release https://github.com/octokit/graphql.js/pull/84, we can update this PR to require the new version, then this is good to go

**Comment by gr2m** [comment]
Actually it's a sub dependency that should be used automatically so we are good to go 👍

**Pull request merged**
